A/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('rating_comments/', include('rating_comments.urls', namespace='rating_comments')),
    path('ckeditor5/', include('django_ckeditor_5.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.UserRegisterView.as_view(), name='user_register'),
    path('verify/', views.UserRegisterVerifyCodeView.as_view(), name='verify_code'),
    path('resend/', views.ResendOtpCodeView.as_view(), name='resend_code'),
    path('login/', views.UserLoginView.as_view(), name='user_login'),
    path('logout/', views.UserLogoutView.as_view(), name='user_logout'),
    path('user_profile/<int:user_id>/', views.UserProfileView.as_view(), name='user_profile'),
    path('reset/', views.UserPasswordResetView.as_view(), name='reset_password'),
    path('reset/done/', views.UserPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('confirm/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('confirm/complete/', views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('edit_user/', views.EditUserView.as_view(), name='edit_user'),
    path('addresses/', views.ManageAddressView.as_view(), name='manage_addresses'),
]

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.OrderCreateView.as_view(), name='orders_create'),
    path('detail/<int:order_id>/', views.OrderDetailView.as_view(), name='order_detail'),
    path('cart/', views.CartView.as_view(), name='cart'),
    path('cart/add/<int:product_id>/', views.CartAddView.as_view(), name='cart_add'),
    path('cart/remove/<int:product_id>/', views.CartRemoveView.as_view(), name='cart_remove'),
    path('pay/<int:order_id>/', views.OrderPayView.as_view(), name='order_pay'),
    path('verify/', views.OrderVerifyView.as_view(), name='order_verify'),
    path('apply/<int:order_id>/', views.CouponApplyView.as_view(), name='apply_coupon'),
]

accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin
from .manager import UserManager
from django.utils import timezone
from django.conf import settings

class User(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(max_length=200, unique=True)
    phone_number = models.CharField(max_length=11, unique=True)
    username = models.CharField(max_length=200, unique=True)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)

    objects = UserManager()

    USERNAME_FIELD = 'phone_number'
    REQUIRED_FIELDS = ['email', 'username']

    def __str__(self):
        return self.username

    @property
    def is_staff(self):
        return self.is_admin

class OtpCode(models.Model):
    email = models.EmailField(max_length=200, unique=True)
    code = models.PositiveSmallIntegerField()
    created = models.DateTimeField(auto_now_add=True)

    def can_resend(self):
        return timezone.now() > self.created + timezone.timedelta(seconds=30)

    def __str__(self):
        return f'{self.email} - {self.code} - {self.created}'

def user_directory_path(instance, filename):
    return f'profile_pic/{instance.user.id}/{filename}'

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    age = models.PositiveSmallIntegerField(default=0)
    image = models.ImageField(upload_to=user_directory_path, null=True, blank=True)
    full_name = models.CharField(max_length=200, null=True, blank=True)

    def get_image_url(self):
        if self.image:
            return self.image.url
        return settings.STATIC_URL + 'accounts/images/default.jpeg'

    def __str__(self):
        return self.user.username

class Address(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='addresses')
    address = models.TextField(null=True, blank=True)
    postal_code = models.CharField(max_length=25, null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'{self.user} - {self.address} - {self.postal_code}'

accounts/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.core.mail import send_mail
from django.views import View
from .forms import UserRegisterationForm, VerifyCodeForm, UserLoginForm, EditUserForm, AddressForm
from .models import User, OtpCode, Profile, Address
import random
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.mixins import LoginRequiredMixin
from django.conf import settings
from types import SimpleNamespace
from django.contrib.auth import views as auth_view
from django.urls import reverse_lazy
from accounts.tasks import remove_expired_otp_codes

class UserRegisterView(View):
    form_class = UserRegisterationForm
    templates_name = 'accounts/register.html'

    def get(self, request):
        form = self.form_class
        return render(request, template_name=self.templates_name, context={'form': form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            random_code = random.randint(1000, 9999)
            OtpCode.objects.update_or_create(email=form.cleaned_data['email'], defaults={'code': random_code})
            request.session['user_registeration_info'] = {
                'phone_number': form.cleaned_data['phone_number'],
                'email': form.cleaned_data['email'],
                'username': form.cleaned_data['username'],
                'password': form.cleaned_data['password2'],
            }
            send_mail(subject='کد فعال سازی حساب', message=f"کد فعال سازی شما: {random_code}",
                      from_email=settings.EMAIL_HOST_USER,
                      recipient_list=[form.cleaned_data['email']], fail_silently=False)
            messages.success(request, message='کد به ایمیل شما فرستاده شد', extra_tags='success')
            return redirect('accounts:verify_code')
        return render(request, template_name=self.templates_name, context={'form': form})


class UserRegisterVerifyCodeView(View):
    form_class = VerifyCodeForm

    def get(self, request):
        form = self.form_class
        return render(request, template_name='accounts/verify.html', context={'form': form})

    def post(self, request):
        user_session = request.session['user_registeration_info']
        try:
            code_instance = OtpCode.objects.get(email=user_session['email'])
        except OtpCode.DoesNotExist:
            # یعنی کد یا منقضی شده یا هیچ‌وقت وجود نداشته
            messages.error(request, 'کد منقضی شده است. لطفا روی ارسال مجدد کد بزنید', extra_tags='danger')
            return redirect('accounts:verify_code')

        form = self.form_class(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            if cd['code'] == code_instance.code:
                # ایجاد کاربر
                User.objects.create_user(
                    phone_number=user_session['phone_number'],
                    email=user_session['email'],
                    username=user_session['username'],
                    password=user_session['password']
                )

                # لاگین کردن کاربر
                user = authenticate(request, username=user_session['email'], password=user_session['password'])
                if user is not None:
                    login(request, user)
                    code_instance.delete()
                    messages.success(request, message='ثبت نام با موفقیت انجام شد', extra_tags='success')
                    return redirect('home:home')
                else:
                    return redirect('accounts:user_register')
            else:
                messages.error(request, message='کد وارد شده اشتباه است', extra_tags='danger')
                return redirect('accounts:verify_code')

        return redirect('accounts:verify_code')


class ResendOtpCodeView(View):
    def get(self, request):
        user_session = request.session.get('user_registeration_info')
        if not user_session:
            messages.error(request, 'اطلاعات ثبت نام یافت نشد', extra_tags='danger')
            return redirect('accounts:register')
        try:
            code_instance = OtpCode.objects.get(email=user_session['email'])
            if not code_instance.can_resend():
                messages.error(request, 'لطفا 30 ثانیه صبر کنید و دوباره تلاش کنید', extra_tags='danger')
                return redirect('accounts:verify_code')
            code_instance.delete()
        except:
            pass
        random_code = random.randint(1000, 9999)
        OtpCode.objects.create(email=user_session['email'], code=random_code)
        send_mail(subject='کد جدید فعال سازی', message=f"کد فعال سازی شما: {random_code}",
                  from_email=settings.EMAIL_HOST_USER, recipient_list=[user_session['email']], fail_silently=False)
        messages.success(request, 'کد جدید برای شما ارسال شد', extra_tags='success')
        return redirect('accounts:verify_code')


class UserLoginView(View):
    form_class = UserLoginForm
    template_name = 'accounts/login.html'

    def __init__(self):
        super().__init__()
        self.next = None

    def setup(self, request, *args, **kwargs):
        #         (http method) (python get)
        self.next = request.GET.get('next')
        return super().setup(request, *args, **kwargs)

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect('home:home')
        return super().dispatch(request, *args, **kwargs)

    def get(self, request):
        form = self.form_class()
        return render(request, self.template_name, {'form': form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(request, username=cd['email'], password=cd['password'])
            if user is not None:
                login(request, user)
                messages.success(request, 'خوش آمدید', extra_tags='success')
                if self.next:
                    return redirect(self.next)
                return redirect('home:home')
            else:
                messages.error(request, 'ایمیل یا رمز ورود اشتباه است', extra_tags='danger')
        return render(request, self.template_name, {'form': form})


class UserLogoutView(LoginRequiredMixin, View):

    @staticmethod
    def get(request):
        logout(request)
        messages.info(request, 'با موفقیت خارج شدید', extra_tags='info')
        return redirect('home:home')


class UserProfileView(LoginRequiredMixin, View):
    def get(self, request, user_id):
        user = get_object_or_404(User, pk=user_id)
        try:
            profile = user.profile
        except Profile.DoesNotExist:
            profile = SimpleNamespace(image=None, full_name='', age=None)
        return render(request, 'accounts/profile.html', context={'user': user, 'profile': profile})


class EditUserView(LoginRequiredMixin, View):
    form_class = EditUserForm
    template_name = 'accounts/edit_profile.html'

    def get_profile(self, user):
        profile, created = Profile.objects.get_or_create(user=user)
        return profile

    def get(self, request):
        profile = self.get_profile(request.user)
        form = self.form_class(instance=profile, user=request.user)
        return render(request, self.template_name, context={'form': form})

    def post(self, request):
        profile = self.get_profile(request.user)
        form = self.form_class(request.POST, request.FILES, instance=profile, user=request.user)
        if form.is_valid():
            profile = form.save(commit=False)
            if form.cleaned_data.get('remove_image'):
                if profile.image:
                    profile.image.delete(save=False)
                    profile.image = None
                    profile.save()
            else:
                profile.save()

            messages.info(request, 'تغییرات با موفقیت ثبت شد', extra_tags='info')
            return redirect('accounts:user_profile', request.user.id)
        return render(request, self.template_name, context={'form': form})


class UserPasswordResetView(auth_view.PasswordResetView):
    template_name = 'accounts/password_reset_form.html'
    success_url = reverse_lazy('accounts:password_reset_done')
    email_template_name = 'accounts/password_reset_email.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class UserPasswordResetDoneView(auth_view.PasswordResetDoneView):
    template_name = 'accounts/password_reset_done.html'


class PasswordResetConfirmView(auth_view.PasswordResetConfirmView):
    template_name = 'accounts/password_reset_confirm.html'
    success_url = reverse_lazy('accounts:password_reset_complete')


class PasswordResetCompleteView(auth_view.PasswordResetCompleteView):
    template_name = 'accounts/password_reset_complete.html'

class ManageAddressView(LoginRequiredMixin, View):
    template_name = 'accounts/manage_addresses.html'
    form_class = AddressForm

    def get(self, request):
        addresses = request.user.addresses.all()
        form = self.form_class()
        return render(request, self.template_name, context={'addresses': addresses, 'form': form})

    def post(self, request):
        edit_id = request.POST.get('edit_id')
        if edit_id:
            address = get_object_or_404(Address, id=edit_id, user=request.user)
            form = self.form_class(request.POST, instance=address)
        else:
            form = self.form_class(request.POST)
        if form.is_valid():
            addr = form.save(commit=False)
            addr.user = request.user
            addr.save()
            return redirect('accounts:manage_addresses')
        addresses = request.user.addresses.all()
        return render(request, self.template_name, context={'addresses': addresses, 'form': form})

accounts/templates/accounts/custom_clearable_file_input.html
    <input type="{{ widget.type }}" name="{{ widget.name }}" {% include 'django/forms/widgets/attrs.html' %}>

accounts/templates/accounts/edit_profile.html
{% extends 'base.html' %}
{% block title %}
	Edit Profile
{% endblock %}
{% block content %}
    <form action="" method="post" enctype="multipart/form-data" novalidate>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Change" class="btn btn-success">
        <a href="{% url 'accounts:reset_password' %}" class="btn btn-danger">Reset password</a>
    </form>
{% endblock %}

accounts/templates/accounts/login.html
{% extends 'base.html'%}
{% block title %}
	Login
{% endblock %}
{% block content %}
	<form action="" method="post" novalidate>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Login">
    </form>
    <a href="{% url 'accounts:reset_password' %}" class="btn btn-info">فراموشی رمز</a>
{% endblock %}

accounts/templates/accounts/manage_addresses.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
	addresses
{% endblock %}

{% block content %}
<div class="container mt-4">
    <h2 class="mb-4">مدیریت آدرس‌ها</h2>

    <!-- جدول لیست آدرس‌ها -->
    <table class="table table-striped">
        <thead class="table-dark">
            <tr>
                <th>آدرس</th>
                <th>کد پستی</th>
                <th>عملیات</th>
            </tr>
        </thead>
        <tbody>
            {% for addr in addresses %}
            <tr>
                <td>{{ addr.address }}</td>
                <td>{{ addr.postal_code }}</td>
                <td>
                    <button class="btn btn-sm btn-primary edit-btn"
                            data-id="{{ addr.id }}"
                            data-address="{{ addr.address }}"
                            data-postal="{{ addr.postal_code }}">
                        ویرایش
                    </button>
                </td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="3" class="text-center">آدرسی ثبت نشده است.</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

    <hr>

    <!-- فرم اضافه / ویرایش آدرس -->
    <h4 id="form-title">اضافه کردن آدرس جدید</h4>
    <form method="post" id="address-form" class="mt-3">
        {% csrf_token %}
        <input type="hidden" name="edit_id" id="edit_id">

        <div class="mb-3">
            <label for="address" class="form-label">آدرس</label>
            <input type="text" class="form-control" id="address" name="address"
                   value="{{ form.address.value|default_if_none:'' }}">
        </div>

        <div class="mb-3">
            <label for="postal_code" class="form-label">کد پستی</label>
            <input type="text" class="form-control" id="postal_code" name="postal_code"
                   value="{{ form.postal_code.value|default_if_none:'' }}">
        </div>

        <button type="submit" class="btn btn-success" id="submit-btn">ذخیره</button>
        <button type="button" class="btn btn-secondary" id="cancel-btn" style="display:none;">انصراف</button>
    </form>
</div>

<!-- لود JS از static -->
<script src="{% static 'accounts/js/manage_addresses.js' %}"></script>

{% endblock %}

accounts/templates/accounts/password_reset_complete.html
{% extends 'base.html'%}
{% block title %}
	password reset complete
{% endblock %}
{% block content %}
	<p>your password was changed.</p>
{% endblock %}

accounts/templates/accounts/password_reset_confirm.html
{% extends 'base.html'%}
{% block title %}
	password reset confirm
{% endblock %}
{% block content %}
    {% if validlink %}
    	<form action="" method="post" novalidate>
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Change">
        </form>
    {% else %}
        <P>This link is not valid!</P><br>
        <p>Please try again.</p>
    {% endif %}
{% endblock %}

accounts/templates/accounts/password_reset_done.html
{% extends 'base.html'%}
{% block title %}
	password reset done
{% endblock %}
{% block content %}
	<p>We email you.</p>
{% endblock %}

accounts/templates/accounts/password_reset_email.html
سلام
برای بازنشانی رمز عبور ({{ email }}) روی لینک کلیک کنید<
{{ protocol }}://{{ domain }}{% url 'accounts:password_reset_confirm' uidb64=uid token=token%}
اگر شما درخواست نکرده اید این ایمیل را نادیده بگیرید.

accounts/templates/accounts/password_reset_form.html
{% extends 'base.html'%}
{% block title %}
	reset password
{% endblock %}
{% block content %}
	<form action="" method="post" novalidate>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Send">
    </form>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
	Profile
{% endblock %}
{% block extra_js %}
	<script>
        const csrftoken = document.cookie
            .split(', ')
            .find(row => row.startsWith('csrftoken='))
            ?.split('=')[1];
    </script>
{% endblock %}
{% block content %}
    <div class="card">
        {% if profile %}
            <div style="display: flex">
                {% if profile.image %}
                	<img class="card-body" src="{{ profile.image.url }}" alt="profile picture" width="200" style="border-radius: 50%">
                {% else %}
                    <img src="{% static 'accounts/images/default.jpeg'%}" alt="default image" width="200" style="border-radius: 50%">
                {% endif %}
                <h2 class="card-body">{{ user.username }}</h2>
            </div>
            {% if profile.full_name is not None %}
                <p class="card-body">{{ profile.full_name }}</p>
            {% endif %}
            {% if profile.age is not 0 and profile.age is not None %}
                <p class="card-body">{{ profile.age }}</p>
            {% endif %}
            {% if request.user.id == user.id %}
            	<a class="card-body" aria-current="page" href="{% url 'orders:cart' %}">Cart({{ cart|length }})</a>
            {% endif %}
        {% else %}
            <h2 class="card-body">{{ user.username }}</h2>
        {% endif %}
        {% if request.user.id == user.id %}
            <a href="{% url 'accounts:edit_user' %}" class="btn btn-info">Edit profile</a>
            <a href="{% url 'accounts:manage_addresses' %}" class="btn btn-outline-dark">آدرس ها</a>
        {% endif %}
    </div>
{% endblock %}

accounts/templates/accounts/register.html
{% extends 'base.html'%}
{% block title %}
	Register
{% endblock %}
{% block content %}
	<form action="" method="post" novalidate>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Register">
    </form>
{% endblock %}

accounts/templates/accounts/verify.html
{% extends 'base.html'%}
{% block title %}
	Verify code
{% endblock %}
{% block content %}
	<form action="" method="post" novalidate>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Send" class="btn btn-success">
        <a href="{% url 'accounts:resend_code' %}" class="btn btn-info">ارسال دوباره کد</a>
    </form>
{% endblock %}