A/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls', namespace='home')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('orders/', include('orders.urls', namespace='orders')),
    path('rating_comments/', include('rating_comments.urls', namespace='rating_comments')),
    path('ckeditor5/', include('django_ckeditor_5.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('register/', views.UserRegisterView.as_view(), name='user_register'),
    path('verify/', views.UserRegisterVerifyCodeView.as_view(), name='verify_code'),
    path('resend/', views.ResendOtpCodeView.as_view(), name='resend_code'),
    path('login/', views.UserLoginView.as_view(), name='user_login'),
    path('logout/', views.UserLogoutView.as_view(), name='user_logout'),
    path('user_profile/<int:user_id>/', views.UserProfileView.as_view(), name='user_profile'),
    path('reset/', views.UserPasswordResetView.as_view(), name='reset_password'),
    path('reset/done/', views.UserPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('confirm/<uidb64>/<token>/', views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('confirm/complete/', views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('edit_user/', views.EditUserView.as_view(), name='edit_user'),
    path('addresses/', views.ManageAddressView.as_view(), name='manage_addresses'),
]

home/urls.py
from django.urls import path, include, re_path
from . import views

app_name = 'home'

bucket_urls = [
    path('', views.BucketHome.as_view(), name='bucket'),
    re_path(r'^delete_obj/(?P<key>.+)/$', views.DeleteBucketObject.as_view(), name='delete_obj_bucket'),
    re_path(r'^download_obj/(?P<key>.+)/$', views.DownloadBucketObject.as_view(), name='download_obj_bucket'),
]

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('category/<slug:category_slug>/', views.HomeView.as_view(), name='category_filter'),
    path('bucket/', include(bucket_urls)),
    path('<slug:slug>/', views.ProductDetailView.as_view(), name='product_detail'),
]

orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('create/', views.OrderCreateView.as_view(), name='orders_create'),
    path('detail/<int:order_id>/', views.OrderDetailView.as_view(), name='order_detail'),
    path('cart/', views.CartView.as_view(), name='cart'),
    path('cart/add/<int:product_id>/', views.CartAddView.as_view(), name='cart_add'),
    path('cart/remove/<int:product_id>/', views.CartRemoveView.as_view(), name='cart_remove'),
    path('pay/<int:order_id>/', views.OrderPayView.as_view(), name='order_pay'),
    path('verify/', views.OrderVerifyView.as_view(), name='order_verify'),
    path('apply/<int:order_id>/', views.CouponApplyView.as_view(), name='apply_coupon'),
]

templates/inc/messages.html
{% load static %}
{% if messages %}
  <div id="django-messages" class="position-fixed top-0 end-0 p-3" style="z-index:1050;">
    {% for msg in messages %}
      <div class="alert alert-{{ msg.tags }} d-flex align-items-center alert-dismissible fade-show mb-2"
           role="alert"
           data-auto-dismiss="true"
           data-dismiss-delay="4500">  {# delay بر حسب میلی‌ثانیه #}
        <i class="bi me-2" aria-hidden="true"></i>
        <div class="flex-fill">
          {{ msg }}
        </div>
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
    {% endfor %}
  </div>
{% endif %}

templates/inc/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'home:home' %}">HOME</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'orders:cart' %}">Cart({{ cart|length }})</a>
        </li>
        {% if request.user.is_authenticated %}
              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:user_logout' %}">Logout</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'accounts:user_profile' request.user.id%}">Profile</a>
              </li>
              {% if request.user.is_admin %}
                  <li class="nav-item">
                      <a class="nav-link" href="{% url 'home:bucket' %}">Bucket</a>
                  </li>
              {% endif %}
          {% else %}
              <li class="nav-item">
                  <a class="nav-link" href="{% url 'accounts:user_register' %}">Register</a>
              </li>
              <li class="nav-item">
                  <a class="nav-link" href="{% url 'accounts:user_login' %}">Login</a>
              </li>
          {% endif %}
      </ul>
      <form class="d-flex" method="get" id="search-form">
        {{ search_form }}
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>